// File generated by Manual Setup based on google-services.json (Friend's Project)
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // Config Web (Opsional jika hanya pakai Android)
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHoSHaGriWkr_82eNCUBZvIniBzcuaCTo',
    appId: '1:40476879878:android:34dc0ce8e03695717be787',
    messagingSenderId: '40476879878',
    projectId: 'geminiapiaksara',
    storageBucket: 'geminiapiaksara.firebasestorage.app',
  );

  // [PENTING] Data ini DI-COPY dari JSON 'gen-lang-client' Anda

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs9Lv5W4Ot_D9_xinkIv7Z6_VFr3IIvkA',
    appId: '1:40476879878:web:b350bb8043db390e7be787',
    messagingSenderId: '40476879878',
    projectId: 'geminiapiaksara',
    authDomain: 'geminiapiaksara.firebaseapp.com',
    storageBucket: 'geminiapiaksara.firebasestorage.app',
  );

  // Dummy Web Config (Agar tidak error jika tidak sengaja terpanggil)

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUNafZh1RkasRYtrwJVUBS-KcgCr9e3MA',
    appId: '1:40476879878:ios:c4c8956991652ea47be787',
    messagingSenderId: '40476879878',
    projectId: 'geminiapiaksara',
    storageBucket: 'geminiapiaksara.firebasestorage.app',
    androidClientId: '40476879878-30jc19le3197b2koucmvinpqpitmrl95.apps.googleusercontent.com',
    iosClientId: '40476879878-ujoj2rqvkss5v2jdgb1cr68l663u7t7b.apps.googleusercontent.com',
    iosBundleId: 'com.aksara.aksaraaiAssist',
  );

}