import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:shared_preferences/shared_preferences.dart';

// --- PROVIDERS (STATE MANAGEMENT) ---

// 1. Locale Provider (Bahasa)
// Menyimpan preferensi bahasa user di memori HP agar tidak reset saat restart.
final localeProvider = StateNotifierProvider<LocaleNotifier, Locale>((ref) {
  return LocaleNotifier();
});

class LocaleNotifier extends StateNotifier<Locale> {
  LocaleNotifier() : super(const Locale('id')) {
    _loadLocale();
  }

  // Load bahasa dari SharedPreferences saat aplikasi mulai
  Future<void> _loadLocale() async {
    final prefs = await SharedPreferences.getInstance();
    final savedCode = prefs.getString('selected_language');
    if (savedCode != null) {
      state = Locale(savedCode);
    }
  }

  // Ganti bahasa dan simpan ke SharedPreferences
  Future<void> changeLocale(String languageCode) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('selected_language', languageCode);
    state = Locale(languageCode);
  }
}

// 2. Font Size Provider (Ukuran Teks)
final fontSizeProvider = StateProvider<double>((ref) => 1.0);

// 3. Font Family Provider (Jenis Huruf)
final fontFamilyProvider = StateProvider<String>((ref) => 'Plus Jakarta Sans');

// 4. Theme Provider (Dark/Light Mode)
final themeProvider = StateNotifierProvider<ThemeNotifier, ThemeMode>((ref) => ThemeNotifier());

class ThemeNotifier extends StateNotifier<ThemeMode> {
  ThemeNotifier() : super(ThemeMode.system);
  void toggleTheme() {
    state = state == ThemeMode.dark ? ThemeMode.light : ThemeMode.dark;
  }
}

// --- HELPER FUNCTIONS (FUNGSI PENERJEMAH) ---

/// Menerjemahkan key string UI ke bahasa yang dipilih user.
/// Contoh: tr(ref, 'hello') -> 'Halo' (jika ID)
String tr(WidgetRef ref, String key) {
  final locale = ref.watch(localeProvider).languageCode;
  // Fallback ke Bahasa Inggris ('en') jika key tidak ditemukan di bahasa terpilih
  return _localizedValues[locale]?[key] ?? _localizedValues['en']?[key] ?? key;
}

/// Menerjemahkan label objek (hasil deteksi AI)
String translateObject(WidgetRef ref, String label) {
  final locale = ref.watch(localeProvider).languageCode;
  final key = label.toLowerCase().trim();
  
  if (_objectDict.containsKey(key)) {
    return _objectDict[key]?[locale] ?? label;
  }
  return label;
}

// --- KAMUS OBJEK (SMART LENS DATA) ---
// Data ini digunakan untuk menerjemahkan hasil deteksi objek dari TensorFlow/Gemini
const Map<String, Map<String, String>> _objectDict = {
  'laptop': {'id': 'Laptop', 'en': 'Laptop', 'zh': '笔记本电脑', 'ja': 'ノートパソコン', 'ko': '노트북'},
  'computer': {'id': 'Komputer', 'en': 'Computer', 'zh': '电脑', 'ja': 'コンピューター', 'ko': '컴퓨터'},
  'mouse': {'id': 'Mouse', 'en': 'Mouse', 'zh': '鼠标', 'ja': 'マウス', 'ko': '마우스'},
  'keyboard': {'id': 'Keyboard', 'en': 'Keyboard', 'zh': '键盘', 'ja': 'キーボード', 'ko': '키보드'},
  'monitor': {'id': 'Layar Monitor', 'en': 'Monitor', 'zh': '显示器', 'ja': 'モニター', 'ko': '모니터'},
  'mobile phone': {'id': 'HP / Ponsel', 'en': 'Mobile Phone', 'zh': '手机', 'ja': '携帯電話', 'ko': '휴대전화'},
  'cell phone': {'id': 'HP / Ponsel', 'en': 'Cell Phone', 'zh': '手机', 'ja': '携帯電話', 'ko': '휴대전화'},
  'electronic device': {'id': 'Perangkat Elektronik', 'en': 'Electronic Device', 'zh': '电子设备', 'ja': '電子機器', 'ko': '전자 기기'},
  'headphones': {'id': 'Headphone', 'en': 'Headphones', 'zh': '耳机', 'ja': 'ヘッドフォン', 'ko': '헤드폰'},
  'earphones': {'id': 'Earphone / TWS', 'en': 'Earphones', 'zh': '耳机', 'ja': 'イヤホン', 'ko': '이어폰'},
  'audio equipment': {'id': 'Perangkat Audio', 'en': 'Audio Equipment', 'zh': '音频设备', 'ja': 'オーディオ機器', 'ko': '오디오 장비'},
  'mask': {'id': 'Masker', 'en': 'Mask', 'zh': '面具', 'ja': 'マスク', 'ko': '마스크'},
  'glasses': {'id': 'Kacamata', 'en': 'Glasses', 'zh': '眼镜', 'ja': '眼鏡', 'ko': '안경'},
  'sunglasses': {'id': 'Kacamata Hitam', 'en': 'Sunglasses', 'zh': '墨镜', 'ja': 'サングラス', 'ko': '선글라스'},
  'watch': {'id': 'Jam Tangan', 'en': 'Watch', 'zh': '手表', 'ja': '腕時計', 'ko': '시계'},
  'bag': {'id': 'Tas', 'en': 'Bag', 'zh': '包', 'ja': 'バッグ', 'ko': 'かばん'},
  'backpack': {'id': 'Ransel', 'en': 'Backpack', 'zh': '背包', 'ja': 'バックパック', 'ko': '배낭'},
  'shoe': {'id': 'Sepatu', 'en': 'Shoe', 'zh': '鞋', 'ja': '靴', 'ko': '신발'},
  'jeans': {'id': 'Celana Jeans', 'en': 'Jeans', 'zh': '牛仔裤', 'ja': 'ジーンズ', 'ko': '청바지'},
  'shirt': {'id': 'Kemeja/Kaos', 'en': 'Shirt', 'zh': '衬衫', 'ja': 'シャツ', 'ko': '셔츠'},
  'money': {'id': 'Uang', 'en': 'Money', 'zh': '钱', 'ja': 'お金', 'ko': '돈'},
  'cash': {'id': 'Uang Tunai', 'en': 'Cash', 'zh': '现金', 'ja': '現金', 'ko': '현금'},
  'banknote': {'id': 'Uang Kertas', 'en': 'Banknote', 'zh': '钞票', 'ja': '紙幣', 'ko': '지폐'},
  'notebook': {'id': 'Buku Catatan', 'en': 'Notebook', 'zh': '笔记本', 'ja': 'ノート', 'ko': '공책'},
  'book': {'id': 'Buku', 'en': 'Book', 'zh': '书', 'ja': '本', 'ko': '책'},
  'paper': {'id': 'Kertas', 'en': 'Paper', 'zh': '纸', 'ja': '紙', 'ko': '종이'},
  'chair': {'id': 'Kursi', 'en': 'Chair', 'zh': '椅子', 'ja': '椅子', 'ko': '의자'},
  'table': {'id': 'Meja', 'en': 'Table', 'zh': '桌子', 'ja': 'テーブル', 'ko': '탁자'},
  'desk': {'id': 'Meja Kerja', 'en': 'Desk', 'zh': '书桌', 'ja': '机', 'ko': '책상'},
  'bottle': {'id': 'Botol', 'en': 'Bottle', 'zh': '瓶子', 'ja': 'ボトル', 'ko': '병'},
  'cup': {'id': 'Cangkir', 'en': 'Cup', 'zh': '杯子', 'ja': 'カップ', 'ko': '컵'},
  'food': {'id': 'Makanan', 'en': 'Food', 'zh': '食物', 'ja': '食べ物', 'ko': '음식'},
  'drink': {'id': 'Minuman', 'en': 'Drink', 'zh': '饮料', 'ja': '飲み物', 'ko': '음료'},
  'plant': {'id': 'Tanaman', 'en': 'Plant', 'zh': '植物', 'ja': '植物', 'ko': '식물'},
  'person': {'id': 'Orang', 'en': 'Person', 'zh': '人', 'ja': '人', 'ko': '사람'},
};

// --- KAMUS BAHASA UI (5 BAHASA: ID, EN, ZH, JA, KO) ---
const Map<String, Map<String, String>> _localizedValues = {
  
  // ==========================
  // BAHASA INDONESIA (ID)
  // ==========================
  'id': {
    // --- Login & Auth ---
    'login_title': 'OTENTIKASI',
    'login_welcome': 'Selamat Datang',
    'login_subtitle': 'Masuk untuk mengakses asisten cerdas',
    'login_google': 'Masuk dengan Google', // Diperbaiki: 'login_btn_google' -> 'login_google'
    'login_guest': 'Mode Tamu',            // Diperbaiki: 'login_btn_guest' -> 'login_guest'
    'login_bio_divider': 'Atau masuk dengan',
    'login_bio_finger': 'Sidik Jari',
    'login_bio_face': 'Wajah AI',
    'login_switch_account': 'Ganti Akun',
    'login_bio_prompt': 'Verifikasi identitas Anda',
    'login_quick': 'Login Cepat',
    'biometric_setup_hint': 'Khusus pengguna yang sudah setup',
    'login_google_success': 'Login Akun Google Berhasil!', 
    'bio_na': 'Biometrik tidak tersedia',
    'google_fail': 'Login Google Gagal:',
    'logout': 'Keluar',
    'logout_failed': 'Gagal Logout:',
    'delete_account': 'Hapus Akun',
    'delete_account_confirm': 'Yakin hapus akun? Data akan hilang.',
    'delete_account_success': 'Akun dihapus.',
    'delete_account_failed': 'Gagal hapus akun.',

    // --- Settings & Menu ---
    'settings': 'Pengaturan',
    'settings_title': 'Pengaturan',
    'settings_account': 'Akun & Keamanan',
    'settings_face_setup': 'Rekam Wajah AI (10x)',
    'settings_face_desc': 'Tingkatkan akurasi scan',
    'settings_finger_setup': 'Login Sidik Jari',
    'settings_finger_desc': 'Aktifkan sensor HP',
    'settings_general': 'Umum',
    'settings_language': 'Bahasa',
    'settings_theme': 'Tema Tampilan',
    'settings_logout': 'Keluar Aplikasi',
    'lang_changed': 'Bahasa diubah ke',
    'theme_system': 'Ikuti Sistem',
    'theme_light': 'Mode Terang',
    'theme_dark': 'Mode Gelap',

    // --- Face Enrollment ---
    'face_setup_title': 'Perekaman Wajah',
    'face_setup_step': 'Langkah',
    'face_setup_instruction': 'Ikuti instruksi gerakan kepala',
    'face_angle_center': 'Lihat Lurus ke Depan',
    'face_angle_left': 'Toleh Sedikit ke Kiri',
    'face_angle_right': 'Toleh Sedikit ke Kanan',
    'face_angle_up': 'Angkat Dagu Sedikit',
    'face_angle_down': 'Tunduk Sedikit',
    'face_success': 'Wajah Berhasil Didaftarkan!',
    'face_fail': 'Gagal mendeteksi wajah, coba lagi',
    'face_processing': 'Memproses data...',
    'face_login_success': 'Wajah Terdeteksi! Masuk...',
    'face_na': 'Wajah tidak cocok atau tidak terdeteksi.',

    // --- General App UI ---
    'app_name': 'Aksara AI',
    'hello': 'Halo,',
    'explore': 'Jelajahi Fitur',
    'home': 'Beranda',
    'history': 'Riwayat',
    'profile': 'Profil',
    'about_app': 'Tentang Aplikasi',
    'privacy': 'Kebijakan Privasi',
    'language': 'Bahasa',
    'feedback': 'Beri Masukan',
    'cancel': 'Batal',
    'save': 'Simpan',
    'delete': 'Hapus',
    'error': 'Terjadi Kesalahan',
    'success': 'Berhasil',
    'gallery': 'Galeri',
    'camera': 'Kamera',
    'link': 'Tautan',
    'text_copied': 'Teks berhasil disalin',
    'no_history': 'Belum ada riwayat.',
    'no_notif': 'Tidak ada notifikasi.',
    'start_explore': 'Mulai',
    'appearance': 'TAMPILAN',
    'dark_mode': 'Mode Gelap',
    'font_style': 'Gaya Huruf',
    'font_size': 'Ukuran Huruf',
    'system_data': 'SISTEM',
    'clear_cache': 'Bersihkan Cache',
    'cache_desc': 'Hapus data sementara',
    'cache_cleared': 'Cache dibersihkan!',
    'app_version': 'Versi',
    'select_language': 'Pilih Bahasa',
    'edit_name': 'Ubah Nama',
    'name_hint': 'Nama baru',
    'email_fail': 'Gagal membuka aplikasi email',

    // --- Feature: OCR ---
    'ocr_title': 'Scan Teks',
    'ocr_hint': 'Ambil foto atau pilih dari galeri.',
    'ocr_header_ai': 'Hasil AI',
    'ocr_header_raw': 'Hasil Mentah',
    'ocr_copy': 'Salin Teks',
    'ocr_empty': 'Tidak ada teks terdeteksi',
    'feat_ocr': 'Scan OCR',
    'desc_ocr': 'Ekstrak teks',

    // --- Feature: QR Code ---
    'qr_title': 'Scan QR',
    'qr_page_title': 'Pemindai QR Cerdas',
    'qr_hint_box': 'Posisikan QR di kotak',
    'qr_result_found': 'Ditemukan!',
    'qr_content_label': 'Isi:',
    'qr_type_link': 'Website',
    'qr_type_text': 'Teks',
    'qr_btn_open': 'Buka',
    'qr_btn_copy': 'Salin',
    'qr_copied': 'Disalin',
    'qr_invalid_url': 'Link tidak valid',
    'qr_scanning': 'Scanning...',
    'qr_flash': 'Senter',
    'qr_fail': 'Gagal baca QR',
    'feat_qr': 'Scan QR',
    'desc_qr': 'Baca kode QR',

    // --- Feature: Music ---
    'music_title': 'Aksara Songsmith',
    'music_create_title': 'Buat Lagu',
    'music_topic_label': 'Topik',
    'music_topic_hint': 'Contoh: Hujan...',
    'music_genre_label': 'Genre',
    'music_mood_label': 'Mood',
    'music_btn_create': 'Ciptakan',
    'music_btn_loading': 'Mengarang...',
    'music_result_title': 'Hasil Karya',
    'music_copy': 'Salin Lirik',
    'music_error_input': 'Isi topik dulu.',
    'music_error_gen': 'Gagal membuat lagu.',
    'music_trivia': 'Trivia',
    'feat_music': 'Musik AI',
    'desc_music': 'Buat musik',

    // --- Feature: Object Detection ---
    'obj_smart_title': 'Smart Lens AI',
    'obj_title': 'Deteksi Objek',
    'obj_ai_processing': 'Menganalisa...',
    'obj_ai_wait': 'Tunggu...',
    'obj_detected': 'Terdeteksi',
    'obj_analysis_title': 'Analisa',
    'obj_btn_search_more': 'Info Lanjut',
    'obj_tap_instruction': 'Ketuk untuk detail',
    'obj_error_browser': 'Gagal buka browser',
    'obj_scanning': 'Mode Lacak...',
    'obj_count': 'Objek',
    'obj_btn_capture': 'Analisa',
    'obj_result_list': 'Hasil',
    'obj_status': 'Status',
    'obj_no_cam': 'Kamera error',
    'obj_instruction': 'Arahkan & tekan tombol.',
    'obj_empty': 'Kosong',
    'feat_obj': 'Deteksi Objek',
    'desc_obj': 'Kenali benda',

    // --- Feature: Face Recognition ---
    'face_title': 'Pengenalan Wajah',
    'face_btn_capture': 'Analisa',
    'face_result': 'Hasil',
    'face_match_true': 'DIKENALI',
    'face_match_false': 'TIDAK DIKENALI',
    'face_name': 'Nama:',
    'face_similarity': 'Mirip:',
    'face_scanning': 'Mencari...',
    'face_gender': 'Gender',
    'face_age': 'Usia',
    'face_eth': 'Etnis',
    'face_analyzing': 'Menganalisa...',
    'feat_face': 'Deteksi Wajah',
    'desc_face': 'Identifikasi',

    // --- Feature: Assistant ---
    'assist_title': 'Asisten',
    'assist_intro': 'Bisa bantu apa?',
    'assist_hint': 'Ketik pesan...',
    'feat_title_assist': 'Asisten Cerdas',
    'feat_desc_assist': 'Tanya jawab AI.',
    
    // --- Notification & Logs ---
    'notif_name_title': 'Profil',
    'notif_photo_title': 'Profil',
    'notif_name_desc': 'Nama diubah',
    'notif_photo_desc': 'Foto diubah',
    'log_face_title': 'Wajah',
    'log_face_desc': 'Fitur wajah',
    'log_ocr_title': 'OCR',
    'log_ocr_desc': 'Scan teks',
    'log_music_title': 'Musik',
    'log_music_desc': 'Buka musik',
    'log_obj_title': 'Objek',
    'log_obj_desc': 'Deteksi benda',
    'log_qr_title': 'QR',
    'log_qr_desc': 'Scan QR',

    // --- About Page (Expanded) ---
    'about_title': 'Tentang Aplikasi',
    'about_desc_title': 'Apa itu Aksara AI?',
    'about_desc_content': 'Aksara AI adalah asisten cerdas yang menggabungkan kekuatan kecerdasan buatan (Artificial Intelligence) dengan antarmuka yang ramah pengguna. Aplikasi ini dirancang untuk membantu produktivitas harian Anda dengan fitur-fitur canggih seperti analisis teks, pengenalan gambar, pembuatan musik, dan asisten suara yang responsif.\n\nKami percaya bahwa teknologi AI harus dapat diakses oleh semua orang, dari pelajar hingga profesional. Aksara AI terus dikembangkan dengan pembaruan rutin untuk memastikan akurasi dan kinerja terbaik.',
    'about_features_title': 'Fitur Unggulan',
    'feature_chat': 'Chatbot Cerdas (Gemini AI) untuk tanya jawab.',
    'feature_ocr': 'Pemindai Teks & Objek (OCR & Object Detection).',
    'feature_face': 'Pengenalan Wajah dengan estimasi usia & emosi.',
    'feature_qr': 'Pemulihan & Scan QR Code Instan.',
    
    // --- Privacy Policy Page (Expanded) ---
    'privacy_title': 'Kebijakan Privasi',
    'privacy_subtitle': 'Privasi & Keamanan Data Anda adalah Prioritas Kami.',
    'privacy_collection_title': '1. Pengumpulan Data',
    'privacy_collection_content': 'Kami mengumpulkan data minimal yang diperlukan untuk fungsionalitas aplikasi. Ini mencakup akses kamera untuk fitur OCR/Wajah dan mikrofon untuk fitur suara. Kami tidak mengumpulkan data pribadi sensitif tanpa persetujuan eksplisit Anda.',
    'privacy_usage_title': '2. Penggunaan Data',
    'privacy_usage_content': 'Data yang dikumpulkan digunakan semata-mata untuk memproses permintaan AI (seperti mengirim gambar ke server AI untuk dianalisis), meningkatkan akurasi pengenalan wajah, dan menyimpan riwayat chat Anda secara lokal di perangkat atau di cloud yang aman (Firebase).',
    'privacy_security_title': '3. Keamanan',
    'privacy_security_content': 'Kami menggunakan enkripsi standar industri (SSL/TLS) untuk melindungi data Anda saat transit maupun saat disimpan. Autentikasi pengguna dikelola dengan aman melalui Firebase Authentication yang terpercaya.',
    'privacy_contact_title': '4. Hubungi Kami',
    'privacy_contact_content': 'Jika Anda memiliki pertanyaan mengenai kebijakan privasi ini atau ingin mengajukan penghapusan data, silakan hubungi tim dukungan kami melalui menu pengaturan atau email resmi kami.',
  },

  // ==========================
  // ENGLISH (EN)
  // ==========================
  'en': {
    'login_title': 'AUTHENTICATION',
    'login_welcome': 'Welcome Back',
    'login_subtitle': 'Sign in to access AI',
    'login_google': 'Sign in with Google', // Diperbaiki
    'login_guest': 'Guest Mode',            // Diperbaiki
    'login_bio_divider': 'Or sign in with',
    'login_bio_finger': 'Fingerprint',
    'login_bio_face': 'Face AI',
    'login_switch_account': 'Switch Account',
    'login_bio_prompt': 'Verify identity',
    'login_quick': 'Quick Login',
    'biometric_setup_hint': 'For users with setup completed',
    'login_google_success': 'Google Login Successful!',
    'bio_na': 'Biometrics unavailable',
    'google_fail': 'Login Failed:',
    'logout': 'Logout',
    'logout_failed': 'Logout Failed:',
    'delete_account': 'Delete Account',
    'delete_account_confirm': 'Delete account? Data lost forever.',
    'delete_account_success': 'Deleted.',
    'delete_account_failed': 'Failed.',

    'settings': 'Settings',
    'settings_title': 'Settings',
    'settings_account': 'Account & Security',
    'settings_face_setup': 'Enrol Face AI (10x)',
    'settings_face_desc': 'Improve accuracy',
    'settings_finger_setup': 'Fingerprint Login',
    'settings_finger_desc': 'Enable sensor',
    'settings_general': 'General',
    'settings_language': 'Language',
    'settings_theme': 'Theme',
    'settings_logout': 'Logout',
    'lang_changed': 'Language changed to',
    'theme_system': 'System Default',
    'theme_light': 'Light Mode',
    'theme_dark': 'Dark Mode',

    'face_setup_title': 'Face Enrollment',
    'face_setup_step': 'Step',
    'face_setup_instruction': 'Follow instructions',
    'face_angle_center': 'Look Straight',
    'face_angle_left': 'Turn Left',
    'face_angle_right': 'Turn Right',
    'face_angle_up': 'Tilt Up',
    'face_angle_down': 'Tilt Down',
    'face_success': 'Registered Successfully!',
    'face_fail': 'Face not detected',
    'face_processing': 'Processing...',
    'face_login_success': 'Face Detected! Logging in...',
    'face_na': 'Face not matched or detected.',

    'app_name': 'Aksara AI',
    'hello': 'Hello,',
    'explore': 'Explore',
    'home': 'Home',
    'history': 'History',
    'profile': 'Profile',
    'about_app': 'About',
    'privacy': 'Privacy',
    'language': 'Language',
    'feedback': 'Feedback',
    'cancel': 'Cancel',
    'save': 'Save',
    'delete': 'Delete',
    'error': 'Error',
    'success': 'Success',
    'gallery': 'Gallery',
    'camera': 'Camera',
    'link': 'Link',
    'text_copied': 'Copied',
    'no_history': 'No history.',
    'no_notif': 'No notifications.',
    'start_explore': 'Start',
    'appearance': 'APPEARANCE',
    'dark_mode': 'Dark Mode',
    'font_style': 'Font Style',
    'font_size': 'Font Size',
    'system_data': 'SYSTEM',
    'clear_cache': 'Clear Cache',
    'cache_desc': 'Delete temp data',
    'cache_cleared': 'Cleared!',
    'app_version': 'Version',
    'select_language': 'Language',
    'edit_name': 'Edit Name',
    'name_hint': 'New name',
    'email_fail': 'Could not launch email app',

    'ocr_title': 'OCR Scan',
    'ocr_hint': 'Select image.',
    'ocr_header_ai': 'AI Result',
    'ocr_header_raw': 'Raw Result',
    'ocr_copy': 'Copy',
    'ocr_empty': 'No text detected',
    'feat_ocr': 'OCR Scan',
    'desc_ocr': 'Extract text',

    'qr_title': 'QR Scan',
    'qr_page_title': 'Smart QR',
    'qr_hint_box': 'Position QR',
    'qr_result_found': 'Found!',
    'qr_content_label': 'Content:',
    'qr_type_link': 'Link',
    'qr_type_text': 'Text',
    'qr_btn_open': 'Open',
    'qr_btn_copy': 'Copy',
    'qr_copied': 'Copied',
    'qr_invalid_url': 'Invalid Link',
    'qr_scanning': 'Scanning...',
    'qr_flash': 'Flash',
    'qr_fail': 'Failed',
    'feat_qr': 'QR Scan',
    'desc_qr': 'Read QR',

    'music_title': 'Songsmith',
    'music_create_title': 'Compose',
    'music_topic_label': 'Topic',
    'music_topic_hint': 'Ex: Rain...',
    'music_genre_label': 'Genre',
    'music_mood_label': 'Mood',
    'music_btn_create': 'Compose',
    'music_btn_loading': 'Working...',
    'music_result_title': 'Result',
    'music_copy': 'Copy',
    'music_error_input': 'Enter topic.',
    'music_error_gen': 'Failed.',
    'music_trivia': 'Trivia',
    'feat_music': 'AI Music',
    'desc_music': 'Create music',

    'obj_smart_title': 'Smart Lens',
    'obj_title': 'Object Detect',
    'obj_ai_processing': 'Analyzing...',
    'obj_ai_wait': 'Wait...',
    'obj_detected': 'Detected',
    'obj_analysis_title': 'Analysis',
    'obj_btn_search_more': 'Search',
    'obj_tap_instruction': 'Tap to analyze',
    'obj_error_browser': 'Error browser',
    'obj_scanning': 'Tracking...',
    'obj_count': 'Object',
    'obj_btn_capture': 'Analyze',
    'obj_result_list': 'Result',
    'obj_status': 'Status',
    'obj_no_cam': 'No Camera',
    'obj_instruction': 'Shoot.',
    'obj_empty': 'Empty',
    'feat_obj': 'Object ID',
    'desc_obj': 'Identify',

    'face_title': 'Face Recog',
    'face_btn_capture': 'Analyze',
    'face_result': 'Result',
    'face_match_true': 'MATCHED',
    'face_match_false': 'NO MATCH',
    'face_name': 'Name:',
    'face_similarity': 'Conf:',
    'face_scanning': 'Scan...',
    'face_gender': 'Gender',
    'face_age': 'Age',
    'face_eth': 'Ethnicity',
    'face_analyzing': 'Analyzing...',
    'feat_face': 'Face ID',
    'desc_face': 'Identify',

    'assist_title': 'Assistant',
    'assist_intro': 'Help?',
    'assist_hint': 'Type...',
    'feat_title_assist': 'Smart Assistant',
    'feat_desc_assist': 'Q&A AI.',
    
    'notif_name_title': 'Profile',
    'notif_photo_title': 'Profile',
    'notif_name_desc': 'Updated',
    'notif_photo_desc': 'Updated',
    'log_face_title': 'Face',
    'log_face_desc': 'Used Face',
    'log_ocr_title': 'OCR',
    'log_ocr_desc': 'Used OCR',
    'log_music_title': 'Music',
    'log_music_desc': 'Used Music',
    'log_obj_title': 'Object',
    'log_obj_desc': 'Used Object',
    'log_qr_title': 'QR',
    'log_qr_desc': 'Used QR',

    // --- About Page (English) ---
    'about_title': 'About Application',
    'about_desc_title': 'What is Aksara AI?',
    'about_desc_content': 'Aksara AI is an intelligent assistant that combines the power of Artificial Intelligence with a user-friendly interface. This application is designed to boost your daily productivity with advanced features such as text analysis, image recognition, music creation, and a responsive voice assistant.\n\nWe believe that AI technology should be accessible to everyone, from students to professionals. Aksara AI is continuously developed with regular updates to ensure accuracy and top-notch performance.',
    'about_features_title': 'Key Features',
    'feature_chat': 'Smart Chatbot (Gemini AI) for Q&A.',
    'feature_ocr': 'Text & Object Scanner (OCR & Detection).',
    'feature_face': 'Face Recognition with age & emotion estimation.',
    'feature_qr': 'Instant QR Code Recovery & Scanning.',

    // --- Privacy Policy Page (English) ---
    'privacy_title': 'Privacy Policy',
    'privacy_subtitle': 'Your Privacy & Data Security is Our Priority.',
    'privacy_collection_title': '1. Data Collection',
    'privacy_collection_content': 'We collect minimal data required for app functionality. This includes camera access for OCR/Face features and microphone for voice features. We do not collect sensitive personal data without your explicit consent.',
    'privacy_usage_title': '2. Data Usage',
    'privacy_usage_content': 'Collected data is used solely to process AI requests (like sending images to AI servers for analysis), improve face recognition accuracy, and store your chat history locally on the device or in a secure cloud (Firebase).',
    'privacy_security_title': '3. Security',
    'privacy_security_content': 'We use industry-standard encryption (SSL/TLS) to protect your data during transit and storage. User authentication is securely managed via trusted Firebase Authentication.',
    'privacy_contact_title': '4. Contact Us',
    'privacy_contact_content': 'If you have questions regarding this privacy policy or wish to request data deletion, please contact our support team via the settings menu or our official email.',
  },

  // ==========================
  // CHINESE (SIMPLIFIED) (ZH)
  // ==========================
  'zh': {
    'login_title': '身份验证',
    'login_welcome': '欢迎',
    'login_subtitle': '登录助手',
    'login_google': 'Google 登录', // Diperbaiki
    'login_guest': '访客',            // Diperbaiki
    'login_bio_divider': '快速登录',
    'login_bio_finger': '指纹',
    'login_bio_face': '面部',
    'login_switch_account': '切换',
    'login_bio_prompt': '验证身份',
    'login_quick': '快速登录',
    'biometric_setup_hint': '适用于已设置的用户',
    'login_google_success': 'Google 登录成功！',
    'bio_na': '不可用',
    'google_fail': '失败',
    'logout': '登出',
    'logout_failed': '登出失败：',
    'delete_account': '删除账户',
    'delete_account_confirm': '确定删除?',
    'delete_account_success': '已删除',
    'delete_account_failed': '失败',

    'settings': '设置',
    'settings_title': '设置',
    'settings_account': '账户安全',
    'settings_face_setup': '录入面部 (10x)',
    'settings_face_desc': '提高准确性',
    'settings_finger_setup': '指纹登录',
    'settings_finger_desc': '启用传感器',
    'settings_general': '常规',
    'settings_language': '语言',
    'settings_theme': '外观',
    'settings_logout': '退出',
    'lang_changed': '语言更改为',
    'theme_system': '跟随系统',
    'theme_light': '浅色模式',
    'theme_dark': '深色模式',

    'face_setup_title': '面部录入',
    'face_setup_step': '步骤',
    'face_setup_instruction': '跟随指示',
    'face_angle_center': '直视',
    'face_angle_left': '向左',
    'face_angle_right': '向右',
    'face_angle_up': '抬头',
    'face_angle_down': '低头',
    'face_success': '成功!',
    'face_fail': '失败',
    'face_processing': '处理中...',
    'face_login_success': '检测到人脸！登录中...',
    'face_na': '未匹配或未检测到人脸。',

    'app_name': 'Aksara AI',
    'hello': '你好',
    'explore': '探索',
    'home': '首页',
    'history': '历史',
    'profile': '我的',
    'about_app': '关于',
    'privacy': '隐私',
    'language': '语言',
    'feedback': '反馈',
    'cancel': '取消',
    'save': '保存',
    'delete': '删除',
    'error': '错误',
    'success': '成功',
    'gallery': '相册',
    'camera': '相机',
    'link': '链接',
    'text_copied': '已复制',
    'no_history': '无记录',
    'no_notif': '无通知',
    'start_explore': '开始',
    'appearance': '外观',
    'dark_mode': '深色',
    'font_style': '字体',
    'font_size': '大小',
    'system_data': '系统',
    'clear_cache': '清除缓存',
    'cache_desc': '删临时数据',
    'cache_cleared': '已清除',
    'app_version': '版本',
    'select_language': '语言',
    'edit_name': '改名',
    'name_hint': '新名',
    'email_fail': '无法打开邮件应用',

    'ocr_title': 'OCR',
    'ocr_hint': '选图',
    'ocr_header_ai': 'AI结果',
    'ocr_header_raw': '原结果',
    'ocr_copy': '复制',
    'ocr_empty': '无文本',
    'feat_ocr': 'OCR',
    'desc_ocr': '识字',

    'qr_title': 'QR',
    'qr_page_title': 'QR扫描',
    'qr_hint_box': '对准',
    'qr_result_found': '发现!',
    'qr_content_label': '内容',
    'qr_type_link': '链接',
    'qr_type_text': '文本',
    'qr_btn_open': '打开',
    'qr_btn_copy': '复制',
    'qr_copied': '已复制',
    'qr_invalid_url': '无效',
    'qr_scanning': '扫描中',
    'qr_flash': '灯',
    'qr_fail': '失败',
    'feat_qr': 'QR',
    'desc_qr': '扫码',

    'music_title': '作曲家',
    'music_create_title': '创作',
    'music_topic_label': '主题',
    'music_topic_hint': '例如雨',
    'music_genre_label': '流派',
    'music_mood_label': '心情',
    'music_btn_create': '创作',
    'music_btn_loading': '中...',
    'music_result_title': '结果',
    'music_copy': '复制',
    'music_error_input': '输入主题',
    'music_error_gen': '失败',
    'music_trivia': '冷知识',
    'feat_music': '音乐',
    'desc_music': '创作',

    'obj_smart_title': '智能镜头',
    'obj_title': '物体',
    'obj_ai_processing': '分析中...',
    'obj_ai_wait': '稍候',
    'obj_detected': '检测',
    'obj_analysis_title': '分析',
    'obj_btn_search_more': '搜',
    'obj_tap_instruction': '点击',
    'obj_error_browser': '错误',
    'obj_scanning': '追踪',
    'obj_count': '物体',
    'obj_btn_capture': '分析',
    'obj_result_list': '结果',
    'obj_status': '状态',
    'obj_no_cam': '无相机',
    'obj_instruction': '拍',
    'obj_empty': '无',
    'feat_obj': '物体',
    'desc_obj': '识别',

    'face_title': '人脸',
    'face_btn_capture': '分析',
    'face_result': '结果',
    'face_match_true': '匹配',
    'face_match_false': '不匹配',
    'face_name': '名:',
    'face_similarity': '似:',
    'face_scanning': '扫...',
    'face_gender': '性',
    'face_age': '龄',
    'face_eth': '族',
    'face_analyzing': '析...',
    'feat_face': '人脸',
    'desc_face': '识别',

    'assist_title': '助手',
    'assist_intro': '帮您?',
    'assist_hint': '输入...',
    'feat_title_assist': '智能助手',
    'feat_desc_assist': '问答',
    'notif_name_title': '资料',
    'notif_photo_title': '资料',
    'notif_name_desc': '更新',
    'notif_photo_desc': '更新',
    'log_face_title': '人脸',
    'log_face_desc': '用人脸',
    'log_ocr_title': 'OCR',
    'log_ocr_desc': '扫字',
    'log_music_title': '音乐',
    'log_music_desc': '听歌',
    'log_obj_title': '物体',
    'log_obj_desc': '识物',
    'log_qr_title': 'QR',
    'log_qr_desc': '扫码',

    // --- About & Privacy (Chinese) ---
    'about_title': '关于应用',
    'about_desc_title': '什么是 Aksara AI？',
    'about_desc_content': 'Aksara AI 是一款智能助手，结合了人工智能的强大功能与用户友好的界面。该应用程序旨在通过文本分析、图像识别、音乐创作和响应式语音助手等高级功能提高您的日常工作效率。\n\n我们相信人工智能技术应该普及给每个人，从学生到专业人士。Aksara AI 不断开发并定期更新，以确保准确性和最佳性能。',
    'about_features_title': '主要功能',
    'feature_chat': '智能聊天机器人 (Gemini AI)。',
    'feature_ocr': '文本和物体扫描 (OCR)。',
    'feature_face': '带年龄和情绪估算的人脸识别。',
    'feature_qr': '即时二维码恢复与扫描。',
    
    'privacy_title': '隐私政策',
    'privacy_subtitle': '您的隐私与数据安全是我们的首要任务。',
    'privacy_collection_title': '1. 数据收集',
    'privacy_collection_content': '我们仅收集应用功能所需的最低限度数据。这包括 OCR/人脸功能的摄像头访问权限和语音功能的麦克风权限。未经您的明确同意，我们不会收集敏感的个人数据。',
    'privacy_usage_title': '2. 数据使用',
    'privacy_usage_content': '收集的数据仅用于处理 AI 请求（例如将图像发送到 AI 服务器进行分析）、提高人脸识别准确性以及将聊天记录本地存储在设备上或安全的云端（Firebase）中。',
    'privacy_security_title': '3. 安全',
    'privacy_security_content': '我们使用行业标准加密 (SSL/TLS) 来保护您在传输和存储过程中的数据。用户身份验证通过受信任的 Firebase 身份验证进行安全管理。',
    'privacy_contact_title': '4. 联系我们',
    'privacy_contact_content': '如果您对本隐私政策有疑问或希望请求删除数据，请通过设置菜单或我们的官方电子邮件联系我们的支持团队。',
  },

  // ==========================
  // JAPANESE (JA)
  // ==========================
  'ja': {
    'login_title': '認証',
    'login_welcome': 'ようこそ',
    'login_subtitle': 'ログイン',
    'login_google': 'Google', // Diperbaiki
    'login_guest': 'ゲスト',            // Diperbaiki
    'login_bio_divider': '生体認証',
    'login_bio_finger': '指紋',
    'login_bio_face': '顔',
    'login_switch_account': '切替',
    'login_bio_prompt': '確認',
    'login_quick': 'クイックログイン',
    'biometric_setup_hint': '設定済みのユーザー向け',
    'login_google_success': 'Googleログインに成功しました！',
    'bio_na': '不可',
    'google_fail': '失敗',
    'logout': 'ログアウト',
    'logout_failed': 'ログアウト失敗:',
    'delete_account': '削除',
    'delete_account_confirm': '削除?',
    'delete_account_success': '済',
    'delete_account_failed': '失敗',

    'settings': '設定',
    'settings_title': '設定',
    'settings_account': 'アカウント',
    'settings_face_setup': '顔登録 (10x)',
    'settings_face_desc': '精度向上',
    'settings_finger_setup': '指紋',
    'settings_finger_desc': '有効化',
    'settings_general': '一般',
    'settings_language': '言語',
    'settings_theme': 'テーマ',
    'settings_logout': 'ログアウト',
    'lang_changed': '言語を変更しました:',
    'theme_system': 'システム設定',
    'theme_light': 'ライトモード',
    'theme_dark': 'ダークモード',

    'face_setup_title': '顔登録',
    'face_setup_step': 'ステップ',
    'face_setup_instruction': '指示に従う',
    'face_angle_center': '正面',
    'face_angle_left': '左',
    'face_angle_right': '右',
    'face_angle_up': '上',
    'face_angle_down': '下',
    'face_success': '成功!',
    'face_fail': '失敗',
    'face_processing': '処理中...',
    'face_login_success': '顔を検出しました！ログイン中...',
    'face_na': '顔が一致しないか検出されません。',

    'app_name': 'Aksara AI',
    'hello': 'こんにちは',
    'explore': '探索',
    'home': 'ホーム',
    'history': '履歴',
    'profile': 'プロフ',
    'about_app': '情報',
    'privacy': 'プライバシー',
    'language': '言語',
    'feedback': '意見',
    'cancel': '取消',
    'save': '保存',
    'delete': '削除',
    'error': 'エラー',
    'success': '成功',
    'gallery': '画像',
    'camera': 'カメラ',
    'link': 'リンク',
    'text_copied': 'コピー済',
    'no_history': '履歴なし',
    'no_notif': '通知なし',
    'start_explore': '開始',
    'appearance': '外観',
    'dark_mode': 'ダーク',
    'font_style': 'フォント',
    'font_size': 'サイズ',
    'system_data': 'システム',
    'clear_cache': 'キャッシュ',
    'cache_desc': '削除',
    'cache_cleared': '済',
    'app_version': 'Ver',
    'select_language': '言語',
    'edit_name': '名前',
    'name_hint': '新名',
    'email_fail': 'メールアプリを開けません',

    'ocr_title': 'OCR',
    'ocr_hint': '選択',
    'ocr_header_ai': 'AI',
    'ocr_header_raw': '生',
    'ocr_copy': 'コピー',
    'ocr_empty': 'なし',
    'feat_ocr': 'OCR',
    'desc_ocr': '抽出',

    'qr_title': 'QR',
    'qr_page_title': 'QR',
    'qr_hint_box': '合わせる',
    'qr_result_found': '発見!',
    'qr_content_label': '内容',
    'qr_type_link': 'リンク',
    'qr_type_text': '文字',
    'qr_btn_open': '開く',
    'qr_btn_copy': 'コピー',
    'qr_copied': '済',
    'qr_invalid_url': '無効',
    'qr_scanning': '中...',
    'qr_flash': '光',
    'qr_fail': '失敗',
    'feat_qr': 'QR',
    'desc_qr': '読取',

    'music_title': '作曲',
    'music_create_title': '作成',
    'music_topic_label': 'テーマ',
    'music_topic_hint': '例：雨',
    'music_genre_label': 'ジャンル',
    'music_mood_label': 'ムード',
    'music_btn_create': '作成',
    'music_btn_loading': '中...',
    'music_result_title': '結果',
    'music_copy': 'コピー',
    'music_error_input': '入力',
    'music_error_gen': '失敗',
    'music_trivia': 'トリビア',
    'feat_music': '音楽',
    'desc_music': '生成',

    'obj_smart_title': 'レンズ',
    'obj_title': '物体',
    'obj_ai_processing': '分析中...',
    'obj_ai_wait': '待機',
    'obj_detected': '検出',
    'obj_analysis_title': '分析',
    'obj_btn_search_more': '検索',
    'obj_tap_instruction': 'タップ',
    'obj_error_browser': 'エラー',
    'obj_scanning': '追跡',
    'obj_count': '個',
    'obj_btn_capture': '詳細',
    'obj_result_list': '結果',
    'obj_status': '状態',
    'obj_no_cam': 'なし',
    'obj_instruction': '撮影',
    'obj_empty': 'なし',
    'feat_obj': '物体',
    'desc_obj': '識別',

    'face_title': '顔',
    'face_btn_capture': '分析',
    'face_result': '結果',
    'face_match_true': '一致',
    'face_match_false': '不一致',
    'face_name': '名:',
    'face_similarity': '似:',
    'face_scanning': '中...',
    'face_gender': '性',
    'face_age': '齢',
    'face_eth': '族',
    'face_analyzing': '中...',
    'feat_face': '顔',
    'desc_face': '識別',

    'assist_title': '助手',
    'assist_intro': '何?',
    'assist_hint': '入力...',
    'feat_title_assist': '助手',
    'feat_desc_assist': 'Q&A',
    'notif_name_title': 'プロフ',
    'notif_photo_title': 'プロフ',
    'notif_name_desc': '更新',
    'notif_photo_desc': '更新',
    'log_face_title': '顔',
    'log_face_desc': '顔',
    'log_ocr_title': 'OCR',
    'log_ocr_desc': '文字',
    'log_music_title': '音楽',
    'log_music_desc': '音楽',
    'log_obj_title': '物体',
    'log_obj_desc': '物体',
    'log_qr_title': 'QR',
    'log_qr_desc': 'QR',

    // --- About & Privacy (Japanese) ---
    'about_title': 'アプリについて',
    'about_desc_title': 'Aksara AIとは？',
    'about_desc_content': 'Aksara AIは、人工知能の力と使いやすいインターフェースを組み合わせたインテリジェントアシスタントです。このアプリは、テキスト分析、画像認識、音楽作成、応答性の高い音声アシスタントなどの高度な機能により、日々の生産性を向上させるように設計されています。\n\nAI技術は、学生から専門家まで、すべての人がアクセスできるようにすべきであると考えています。Aksara AIは、最高の精度とパフォーマンスを確保するために定期的な更新を行いながら継続的に開発されています。',
    'about_features_title': '主な機能',
    'feature_chat': 'スマートチャットボット (Gemini AI)。',
    'feature_ocr': 'テキストおよびオブジェクトスキャナー。',
    'feature_face': '年齢と感情を推定する顔認識。',
    'feature_qr': 'インスタントQRコードの復元とスキャン。',
    
    'privacy_title': 'プライバシーポリシー',
    'privacy_subtitle': 'お客様のプライバシーとデータセキュリティは私たちの優先事項です。',
    'privacy_collection_title': '1. データ収集',
    'privacy_collection_content': 'アプリの機能に必要な最小限のデータを収集します。これには、OCR/顔機能のカメラアクセスと音声機能のマイクが含まれます。明示的な同意なしに機密性の高い個人データを収集することはありません。',
    'privacy_usage_title': '2. データ利用',
    'privacy_usage_content': '収集されたデータは、AIリクエストの処理（画像をAIサーバーに送信して分析するなど）、顔認識の精度の向上、チャット履歴のデバイスへのローカル保存または安全なクラウド（Firebase）への保存のみに使用されます。',
    'privacy_security_title': '3. セキュリティ',
    'privacy_security_content': '業界標準の暗号化（SSL/TLS）を使用して、転送中および保存中のデータを保護します。ユーザー認証は、信頼できるFirebase認証を通じて安全に管理されます。',
    'privacy_contact_title': '4. お問い合わせ',
    'privacy_contact_content': 'このプライバシーポリシーについて質問がある場合、またはデータの削除をリクエストしたい場合は、設定メニューまたは公式メールを通じてサポートチームにお問い合わせください。',
  },

  // ==========================
  // KOREAN (KO)
  // ==========================
  'ko': {
    'login_title': '인증',
    'login_welcome': '환영',
    'login_subtitle': '로그인',
    'login_google': 'Google', // Diperbaiki
    'login_guest': '게스트',            // Diperbaiki
    'login_bio_divider': '생체',
    'login_bio_finger': '지문',
    'login_bio_face': '얼굴',
    'login_switch_account': '전환',
    'login_bio_prompt': '확인',
    'login_quick': '빠른 로그인',
    'biometric_setup_hint': '설정이 완료된 사용자용',
    'login_google_success': 'Google 로그인 성공!',
    'bio_na': '불가',
    'google_fail': '실패',
    'logout': '로그아웃',
    'logout_failed': '로그아웃 실패:',
    'delete_account': '삭제',
    'delete_account_confirm': '삭제?',
    'delete_account_success': '완료',
    'delete_account_failed': '실패',

    'settings': '설정',
    'settings_title': '설정',
    'settings_account': '계정',
    'settings_face_setup': '얼굴 등록 (10x)',
    'settings_face_desc': '정확도 향상',
    'settings_finger_setup': '지문',
    'settings_finger_desc': '활성화',
    'settings_general': '일반',
    'settings_language': '언어',
    'settings_theme': '테마',
    'settings_logout': '로그아웃',
    'lang_changed': '언어가 변경되었습니다:',
    'theme_system': '시스템 기본값',
    'theme_light': '라이트 모드',
    'theme_dark': '다크 모드',

    'face_setup_title': '등록',
    'face_setup_step': '단계',
    'face_setup_instruction': '지시 따름',
    'face_angle_center': '정면',
    'face_angle_left': '왼쪽',
    'face_angle_right': '오른쪽',
    'face_angle_up': '위',
    'face_angle_down': '아래',
    'face_success': '성공!',
    'face_fail': '실패',
    'face_processing': '처리중...',
    'face_login_success': '얼굴 감지됨! 로그인 중...',
    'face_na': '얼굴이 일치하지 않거나 감지되지 않았습니다.',

    'app_name': 'Aksara AI',
    'hello': '안녕',
    'explore': '탐색',
    'home': '홈',
    'history': '기록',
    'profile': '프로필',
    'about_app': '정보',
    'privacy': '프라이버시',
    'language': '언어',
    'feedback': '피드백',
    'cancel': '취소',
    'save': '저장',
    'delete': '삭제',
    'error': '오류',
    'success': '성공',
    'gallery': '갤러리',
    'camera': '카메라',
    'link': '링크',
    'text_copied': '복사됨',
    'no_history': '없음',
    'no_notif': '없음',
    'start_explore': '시작',
    'appearance': '화면',
    'dark_mode': '다크',
    'font_style': '글꼴',
    'font_size': '크기',
    'system_data': '시스템',
    'clear_cache': '캐시',
    'cache_desc': '삭제',
    'cache_cleared': '완료',
    'app_version': '버전',
    'select_language': '언어',
    'edit_name': '이름',
    'name_hint': '새 이름',
    'email_fail': '이메일 앱을 열 수 없습니다',

    'ocr_title': 'OCR',
    'ocr_hint': '선택',
    'ocr_header_ai': 'AI',
    'ocr_header_raw': '원문',
    'ocr_copy': '복사',
    'ocr_empty': '없음',
    'feat_ocr': 'OCR',
    'desc_ocr': '추출',

    'qr_title': 'QR',
    'qr_page_title': 'QR',
    'qr_hint_box': '맞춤',
    'qr_result_found': '발견!',
    'qr_content_label': '내용',
    'qr_type_link': '링크',
    'qr_type_text': '텍스트',
    'qr_btn_open': '열기',
    'qr_btn_copy': '복사',
    'qr_copied': '됨',
    'qr_invalid_url': '무효',
    'qr_scanning': '스캔중',
    'qr_flash': '플래시',
    'qr_fail': '실패',
    'feat_qr': 'QR',
    'desc_qr': '스캔',

    'music_title': '작곡',
    'music_create_title': '생성',
    'music_topic_label': '주제',
    'music_topic_hint': '예: 비',
    'music_genre_label': '장르',
    'music_mood_label': '분위기',
    'music_btn_create': '작곡',
    'music_btn_loading': '중...',
    'music_result_title': '결과',
    'music_copy': '복사',
    'music_error_input': '입력',
    'music_error_gen': '실패',
    'music_trivia': '상식',
    'feat_music': '음악',
    'desc_music': '생성',

    'obj_smart_title': '렌즈',
    'obj_title': '객체',
    'obj_ai_processing': '분석중...',
    'obj_ai_wait': '대기',
    'obj_detected': '감지',
    'obj_analysis_title': '분석',
    'obj_btn_search_more': '검색',
    'obj_tap_instruction': '탭',
    'obj_error_browser': '오류',
    'obj_scanning': '추적',
    'obj_count': '개',
    'obj_btn_capture': '상세',
    'obj_result_list': '결과',
    'obj_status': '상태',
    'obj_no_cam': '없음',
    'obj_instruction': '촬영',
    'obj_empty': '없음',
    'feat_obj': '객체',
    'desc_obj': '식별',

    'face_title': '얼굴',
    'face_btn_capture': '분석',
    'face_result': '결과',
    'face_match_true': '일치',
    'face_match_false': '불일치',
    'face_name': '이름:',
    'face_similarity': '유사:',
    'face_scanning': '스캔...',
    'face_gender': '성',
    'face_age': '나이',
    'face_eth': '인종',
    'face_analyzing': '분석...',
    'feat_face': '얼굴',
    'desc_face': '식별',

    'assist_title': '비서',
    'assist_intro': '도움?',
    'assist_hint': '입력...',
    'feat_title_assist': '비서',
    'feat_desc_assist': '문답',
    'notif_name_title': '프로필',
    'notif_photo_title': '프로필',
    'notif_name_desc': '업데이트',
    'notif_photo_desc': '업데이트',
    'log_face_title': '얼굴',
    'log_face_desc': '사용',
    'log_ocr_title': 'OCR',
    'log_ocr_desc': '사용',
    'log_music_title': '음악',
    'log_music_desc': '사용',
    'log_obj_title': '객체',
    'log_obj_desc': '사용',
    'log_qr_title': 'QR',
    'log_qr_desc': '사용',

    // --- About & Privacy (Korean) ---
    'about_title': '앱 정보',
    'about_desc_title': 'Aksara AI란 무엇인가요?',
    'about_desc_content': 'Aksara AI는 인공 지능의 힘과 사용자 친화적인 인터페이스를 결합한 지능형 비서입니다. 이 애플리케이션은 텍스트 분석, 이미지 인식, 음악 생성 및 반응형 음성 비서와 같은 고급 기능으로 일일 생산성을 높이도록 설계되었습니다.\n\n우리는 AI 기술이 학생부터 전문가까지 모든 사람이 접근할 수 있어야 한다고 믿습니다. Aksara AI는 정확성과 최고의 성능을 보장하기 위해 정기적인 업데이트를 통해 지속적으로 개발되고 있습니다.',
    'about_features_title': '주요 기능',
    'feature_chat': '스마트 챗봇 (Gemini AI).',
    'feature_ocr': '텍스트 및 객체 스캐너 (OCR).',
    'feature_face': '나이 및 감정 추정을 통한 얼굴 인식.',
    'feature_qr': '즉각적인 QR 코드 복구 및 스캔.',
    
    'privacy_title': '개인정보 처리방침',
    'privacy_subtitle': '귀하의 개인정보 및 데이터 보안은 우리의 우선순위입니다.',
    'privacy_collection_title': '1. 데이터 수집',
    'privacy_collection_content': '우리는 앱 기능에 필요한 최소한의 데이터를 수집합니다. 여기에는 OCR/얼굴 기능을 위한 카메라 액세스 및 음성 기능을 위한 마이크가 포함됩니다. 귀하의 명시적인 동의 없이 민감한 개인 데이터를 수집하지 않습니다.',
    'privacy_usage_title': '2. 데이터 사용',
    'privacy_usage_content': '수집된 데이터는 AI 요청 처리(분석을 위해 이미지를 AI 서버로 전송 등), 얼굴 인식 정확도 향상, 채팅 기록을 기기에 로컬로 저장하거나 안전한 클라우드(Firebase)에 저장하는 데에만 사용됩니다.',
    'privacy_security_title': '3. 보안',
    'privacy_security_content': '우리는 전송 및 저장 중인 데이터를 보호하기 위해 업계 표준 암호화(SSL/TLS)를 사용합니다. 사용자 인증은 신뢰할 수 있는 Firebase Authentication을 통해 안전하게 관리됩니다.',
    'privacy_contact_title': '4. 문의하기',
    'privacy_contact_content': '이 개인정보 처리방침에 대해 질문이 있거나 데이터 삭제를 요청하려면 설정 메뉴나 공식 이메일을 통해 지원팀에 문의하십시오。',
  },
};