import 'dart:ui';
import 'package:flutter_riverpod/flutter_riverpod.dart';

final localeProvider = StateProvider<Locale>((ref) => const Locale('id'));

String tr(WidgetRef ref, String key) {
  final locale = ref.watch(localeProvider);
  return AppTranslations.getText(locale.languageCode, key);
}

class AppTranslations {
  static String getText(String code, String key) {
    return _localizedValues[code]?[key] ?? _localizedValues['en']?[key] ?? key;
  }

  static final Map<String, Map<String, String>> _localizedValues = {
    // --- INDONESIA ---
    'id': {
      // General
      'home': 'Beranda', 'history': 'Riwayat', 'profile': 'Profil',
      'hello': 'Halo,',
      'settings': 'Pengaturan', 'about_app': 'Tentang Aplikasi',
      'privacy': 'Kebijakan Privasi',
      'language': 'Bahasa', 'logout': 'Keluar', 'delete_account': 'Hapus Akun',
      'feedback': 'Beri Masukan',
      'gallery': 'Galeri', 'camera': 'Kamera', 'cancel': 'Batal',
      'save': 'Simpan', 'close': 'Tutup',
      'error': 'Terjadi Kesalahan', 'success': 'Berhasil',
      'loading': 'Memuat...',

      // Object Detection
      'obj_title': 'Deteksi Objek',
      'obj_fps': 'FPS', 'obj_count': 'Jumlah', 'obj_status': 'Status',
      'obj_scanning': 'Memindai...',

      // OCR
      'ocr_title': 'Pemindai Dokumen',
      'ocr_hint': 'Ambil foto berisi teks...',
      'ocr_header_ai': 'Hasil AI (Dirapikan)',
      'ocr_header_raw': 'Teks Asli (Mentah)',

      // Face Recognition
      'face_title': 'Pengenalan Wajah',
      'face_btn_capture': 'Ambil Foto',
      'face_processing': 'Menganalisis...',
      'face_result': 'Hasil Analisis',
      'face_match_true': 'Wajah Cocok!',
      'face_match_false': 'Wajah Tidak Dikenali',
      'face_similarity': 'Kemiripan',
      'face_name': 'Nama:',

      // QR Scanner
      'qr_title': 'QR Scanner',
      'qr_flash': 'Senter',
      'qr_gallery': 'Ambil Gambar',
      'qr_copy': 'Salin',
      'qr_open': 'Buka Link',
      'qr_result': 'Hasil Scan:',
      'qr_fail': 'QR Code tidak ditemukan',
      'text_copied': 'Teks disalin ke clipboard',

      // Music Player
      'music_title': 'Lirik & Musik',
      'music_search_hint': 'Cari judul lagu...',
      'music_translate': 'Terjemahkan Lirik',
      'music_translating': 'Menerjemahkan...',
      'music_empty': 'Lirik belum tersedia',
      'music_no_song': 'Tidak ada lagu',
      'music_artist_hint': 'Cari lagu untuk memutar',

      // Main Menu Descriptions
      'feat_face': 'Pengenalan Wajah',
      'desc_face': 'Login aman & verifikasi identitas.',
      'feat_ocr': 'OCR & Terjemahan',
      'desc_ocr': 'Scan dokumen jadi teks digital.',
      'feat_music': 'Pencari Lirik', 'desc_music': 'Cari lirik lagu otomatis.',
      'feat_obj': 'Deteksi Objek', 'desc_obj': 'Kenali benda di sekitar.',
      'feat_qr': 'QR Scanner', 'desc_qr': 'Scan barcode & QR cepat.',

      // ... (Keep previous generic keys if needed) ...
      'assist_title': 'Aksara AI', 'assist_intro': 'Bantuan AI',
      'assist_hint': 'Bicara...',
      'app_desc': 'Aksara AI membantu produktivitas harianmu.',
      'purpose_title': 'Tujuan', 'purpose_desc': 'Proyek Akhir PNJ.',
      'policy_intro_title': 'Privasi',
      'policy_intro_body': 'Kami menjaga data Anda.',
      'notif_name_title': 'Info', 'notif_name_desc': 'Nama berubah.',
      'notif_photo_title': 'Info', 'notif_photo_desc': 'Foto berubah.',
      'no_notif': 'Kosong', 'select_language': 'Pilih Bahasa',
    },

    // --- ENGLISH ---
    'en': {
      'home': 'Home',
      'history': 'History',
      'profile': 'Profile',
      'hello': 'Hello,',
      'settings': 'Settings',
      'about_app': 'About App',
      'privacy': 'Privacy Policy',
      'language': 'Language',
      'logout': 'Logout',
      'delete_account': 'Delete Account',
      'feedback': 'Feedback',
      'gallery': 'Gallery',
      'camera': 'Camera',
      'cancel': 'Cancel',
      'save': 'Save',
      'close': 'Close',
      'error': 'Error',
      'success': 'Success',
      'loading': 'Loading...',
      'obj_title': 'Object Detection',
      'obj_fps': 'FPS',
      'obj_count': 'Count',
      'obj_status': 'Status',
      'obj_scanning': 'Scanning...',
      'ocr_title': 'Document Scanner',
      'ocr_hint': 'Take a photo with text...',
      'ocr_header_ai': 'AI Enhanced',
      'ocr_header_raw': 'Raw Text',
      'face_title': 'Face Recognition',
      'face_btn_capture': 'Capture Face',
      'face_processing': 'Analyzing...',
      'face_result': 'Analysis Result',
      'face_match_true': 'Face Matched!',
      'face_match_false': 'Face Not Recognized',
      'face_similarity': 'Similarity',
      'face_name': 'Name:',
      'qr_title': 'QR Scanner',
      'qr_flash': 'Flash',
      'qr_gallery': 'Pick Image',
      'qr_copy': 'Copy',
      'qr_open': 'Open Link',
      'qr_result': 'Scan Result:',
      'qr_fail': 'No QR Code found',
      'text_copied': 'Copied to clipboard',
      'music_title': 'Lyrics & Music',
      'music_search_hint': 'Search song title...',
      'music_translate': 'Translate Lyrics',
      'music_translating': 'Translating...',
      'music_empty': 'No lyrics available',
      'music_no_song': 'No Song Playing',
      'music_artist_hint': 'Search to play',
      'feat_face': 'Face Recognition',
      'desc_face': 'Secure login & identity verification.',
      'feat_ocr': 'OCR & Translate',
      'desc_ocr': 'Digitize documents instantly.',
      'feat_music': 'Lyrics Finder',
      'desc_music': 'Find lyrics automatically.',
      'feat_obj': 'Object Detection',
      'desc_obj': 'Identify objects nearby.',
      'feat_qr': 'QR Scanner',
      'desc_qr': 'Quick barcode scanner.',
      'assist_title': 'Aksara AI',
      'assist_intro': 'AI Help',
      'assist_hint': 'Speak...',
      'app_desc': 'Aksara AI boosts productivity.',
      'purpose_title': 'Purpose',
      'purpose_desc': 'PNJ Final Project.',
      'policy_intro_title': 'Privacy',
      'policy_intro_body': 'We protect your data.',
      'notif_name_title': 'Info',
      'notif_name_desc': 'Name updated.',
      'notif_photo_title': 'Info',
      'notif_photo_desc': 'Photo updated.',
      'no_notif': 'Empty',
      'select_language': 'Select Language',
    },

    // --- MANDARIN (ZH) ---
    'zh': {
      'home': '主页',
      'history': '历史',
      'profile': '我的',
      'hello': '你好,',
      'settings': '设置',
      'about_app': '关于应用',
      'privacy': '隐私政策',
      'language': '语言',
      'logout': '退出',
      'delete_account': '删除账户',
      'feedback': '反馈',
      'gallery': '相册',
      'camera': '相机',
      'cancel': '取消',
      'save': '保存',
      'close': '关闭',
      'error': '错误',
      'success': '成功',
      'loading': '加载中...',
      'obj_title': '物体检测',
      'obj_fps': '帧率',
      'obj_count': '数量',
      'obj_status': '状态',
      'obj_scanning': '扫描中...',
      'ocr_title': '文档扫描',
      'ocr_hint': '拍摄包含文字的照片...',
      'ocr_header_ai': 'AI 优化结果',
      'ocr_header_raw': '原始文本',
      'face_title': '人脸识别',
      'face_btn_capture': '拍摄人脸',
      'face_processing': '分析中...',
      'face_result': '分析结果',
      'face_match_true': '匹配成功！',
      'face_match_false': '未识别',
      'face_similarity': '相似度',
      'face_name': '姓名:',
      'qr_title': '二维码扫描',
      'qr_flash': '手电筒',
      'qr_gallery': '选择图片',
      'qr_copy': '复制',
      'qr_open': '打开链接',
      'qr_result': '扫描结果:',
      'qr_fail': '未发现二维码',
      'text_copied': '已复制到剪贴板',
      'music_title': '歌词与音乐',
      'music_search_hint': '搜索歌名...',
      'music_translate': '翻译歌词',
      'music_translating': '翻译中...',
      'music_empty': '暂无歌词',
      'music_no_song': '无歌曲播放',
      'music_artist_hint': '搜索以播放',
      'feat_face': '人脸识别',
      'desc_face': '安全登录与身份验证。',
      'feat_ocr': '文字识别',
      'desc_ocr': '将文档转换为数字文本。',
      'feat_music': '歌词搜索',
      'desc_music': '自动查找歌词。',
      'feat_obj': '物体检测',
      'desc_obj': '识别周围物体。',
      'feat_qr': '二维码',
      'desc_qr': '快速扫描条码。',
      'assist_title': 'Aksara AI',
      'assist_intro': 'AI 助手',
      'assist_hint': '说话...',
      'app_desc': 'Aksara AI 提升效率。',
      'purpose_title': '目的',
      'purpose_desc': 'PNJ 期末项目。',
      'policy_intro_title': '隐私',
      'policy_intro_body': '保护您的数据。',
      'notif_name_title': '通知',
      'notif_name_desc': '名称已更新。',
      'notif_photo_title': '通知',
      'notif_photo_desc': '照片已更新。',
      'no_notif': '空',
      'select_language': '选择语言',
    },

    // --- JAPANESE (JA) ---
    'ja': {
      'home': 'ホーム',
      'history': '履歴',
      'profile': 'プロフィール',
      'hello': 'こんにちは',
      'settings': '設定',
      'about_app': 'アプリについて',
      'privacy': 'プライバシー',
      'language': '言語',
      'logout': 'ログアウト',
      'delete_account': '削除',
      'feedback': 'フィードバック',
      'gallery': 'ギャラリー',
      'camera': 'カメラ',
      'cancel': 'キャンセル',
      'save': '保存',
      'close': '閉じる',
      'error': 'エラー',
      'success': '成功',
      'loading': '読み込み中...',
      'obj_title': '物体検知',
      'obj_fps': 'FPS',
      'obj_count': '数',
      'obj_status': '状態',
      'obj_scanning': 'スキャン中...',
      'ocr_title': 'ドキュメントスキャン',
      'ocr_hint': '文字を含む写真を撮る...',
      'ocr_header_ai': 'AI 結果',
      'ocr_header_raw': '元のテキスト',
      'face_title': '顔認証',
      'face_btn_capture': '撮影',
      'face_processing': '分析中...',
      'face_result': '結果',
      'face_match_true': '一致しました！',
      'face_match_false': '認識できません',
      'face_similarity': '類似度',
      'face_name': '名前:',
      'qr_title': 'QRスキャナー',
      'qr_flash': 'ライト',
      'qr_gallery': '画像選択',
      'qr_copy': 'コピー',
      'qr_open': '開く',
      'qr_result': '結果:',
      'qr_fail': 'QRコードなし',
      'text_copied': 'コピーしました',
      'music_title': '歌詞と音楽',
      'music_search_hint': '曲名を検索...',
      'music_translate': '歌詞を翻訳',
      'music_translating': '翻訳中...',
      'music_empty': '歌詞なし',
      'music_no_song': '再生中の曲なし',
      'music_artist_hint': '検索して再生',
      'feat_face': '顔認証',
      'desc_face': '安全なログイン。',
      'feat_ocr': '文字認識',
      'desc_ocr': '文書をデジタル化。',
      'feat_music': '歌詞検索',
      'desc_music': '歌詞を自動検索。',
      'feat_obj': '物体検知',
      'desc_obj': '物体を識別。',
      'feat_qr': 'QRスキャン',
      'desc_qr': '高速スキャナー。',
      'assist_title': 'Aksara AI',
      'assist_intro': 'AI ヘルプ',
      'assist_hint': '話す...',
      'app_desc': '生産性を向上させます。',
      'purpose_title': '目的',
      'purpose_desc': 'PNJ 最終プロジェクト。',
      'policy_intro_title': 'プライバシー',
      'policy_intro_body': 'データを保護します。',
      'notif_name_title': '通知',
      'notif_name_desc': '名前更新完了。',
      'notif_photo_title': '通知',
      'notif_photo_desc': '写真更新完了。',
      'no_notif': 'なし',
      'select_language': '言語選択',
    },

    // --- KOREAN (KO) ---
    'ko': {
      'home': '홈',
      'history': '기록',
      'profile': '프로필',
      'hello': '안녕하세요',
      'settings': '설정',
      'about_app': '앱 정보',
      'privacy': '개인정보',
      'language': '언어',
      'logout': '로그아웃',
      'delete_account': '삭제',
      'feedback': '피드백',
      'gallery': '갤러리',
      'camera': '카메라',
      'cancel': '취소',
      'save': '저장',
      'close': '닫기',
      'error': '오류',
      'success': '성공',
      'loading': '로딩 중...',
      'obj_title': '사물 감지',
      'obj_fps': 'FPS',
      'obj_count': '수량',
      'obj_status': '상태',
      'obj_scanning': '스캔 중...',
      'ocr_title': '문서 스캐너',
      'ocr_hint': '텍스트가 있는 사진 촬영...',
      'ocr_header_ai': 'AI 결과',
      'ocr_header_raw': '원본 텍스트',
      'face_title': '얼굴 인식',
      'face_btn_capture': '촬영',
      'face_processing': '분석 중...',
      'face_result': '결과',
      'face_match_true': '일치함!',
      'face_match_false': '인식 불가',
      'face_similarity': '유사도',
      'face_name': '이름:',
      'qr_title': 'QR 스캐너',
      'qr_flash': '플래시',
      'qr_gallery': '이미지 선택',
      'qr_copy': '복사',
      'qr_open': '링크 열기',
      'qr_result': '스캔 결과:',
      'qr_fail': 'QR 코드 없음',
      'text_copied': '클립보드에 복사됨',
      'music_title': '가사 및 음악',
      'music_search_hint': '노래 제목 검색...',
      'music_translate': '가사 번역',
      'music_translating': '번역 중...',
      'music_empty': '가사 없음',
      'music_no_song': '재생 중인 곡 없음',
      'music_artist_hint': '검색하여 재생',
      'feat_face': '얼굴 인식',
      'desc_face': '보안 로그인.',
      'feat_ocr': '텍스트 인식',
      'desc_ocr': '문서 디지털화.',
      'feat_music': '가사 찾기',
      'desc_music': '가사 자동 검색.',
      'feat_obj': '사물 감지',
      'desc_obj': '사물 식별.',
      'feat_qr': 'QR 스캔',
      'desc_qr': '빠른 스캐너.',
      'assist_title': 'Aksara AI',
      'assist_intro': 'AI 도움말',
      'assist_hint': '말하기...',
      'app_desc': '생산성을 높입니다.',
      'purpose_title': '목적',
      'purpose_desc': 'PNJ 기말 프로젝트.',
      'policy_intro_title': '개인정보',
      'policy_intro_body': '데이터를 보호합니다.',
      'notif_name_title': '알림',
      'notif_name_desc': '이름 업데이트됨.',
      'notif_photo_title': '알림',
      'notif_photo_desc': '사진 업데이트됨.',
      'no_notif': '비어 있음',
      'select_language': '언어 선택',
    },
  };
}
