import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

// --- Providers ---
// Default Locale Indonesia
final localeProvider = StateProvider<Locale>((ref) => const Locale('id'));
final fontSizeProvider = StateProvider<double>((ref) => 1.0);
// Default Font
final fontFamilyProvider = StateProvider<String>((ref) => 'Plus Jakarta Sans');
final themeProvider = StateNotifierProvider<ThemeNotifier, ThemeMode>((ref) => ThemeNotifier());

class ThemeNotifier extends StateNotifier<ThemeMode> {
  ThemeNotifier() : super(ThemeMode.system);

  void toggleTheme() {
    state = state == ThemeMode.dark ? ThemeMode.light : ThemeMode.dark;
  }
}

String tr(WidgetRef ref, String key) {
  final locale = ref.watch(localeProvider).languageCode;
  return _localizedValues[locale]?[key] ?? _localizedValues['en']?[key] ?? key;
}

// --- KAMUS BAHASA LENGKAP (ID, EN, ZH, JA, KO) ---
const Map<String, Map<String, String>> _localizedValues = {
  // ================= BAHASA INDONESIA (ID) =================
  'id': {
    // General UI
    'app_name': 'Aksara AI',
    'hello': 'Halo,',
    'explore': 'Jelajahi Fitur',
    'home': 'Beranda',
    'history': 'Riwayat',
    'profile': 'Profil',
    'settings': 'Pengaturan',
    'about_app': 'Tentang Aplikasi',
    'privacy': 'Kebijakan Privasi',
    'language': 'Bahasa',
    'feedback': 'Beri Masukan',
    'logout': 'Keluar',
    'delete_account': 'Hapus Akun',
    'cancel': 'Batal',
    'save': 'Simpan',
    'no_history': 'Belum ada riwayat aktivitas.',
    'no_notif': 'Tidak ada notifikasi baru.',
    
    // About Page - Tabs & Content
    'tab_bg': 'Latar Belakang',
    'tab_feat': 'Fitur Utama',
    'tab_dev': 'Pengembang',
    'about_bg_text': 'Aksara AI lahir dari sebuah ide sederhana: bagaimana jika setiap orang memiliki asisten pribadi yang selalu siap membantu kapan saja?\n\nDi tengah derasnya arus informasi, kami percaya bahwa teknologi Artificial Intelligence harusnya memudahkan, bukan membingungkan. Aksara AI dibangun untuk menjadi teman cerdasmu dalam belajar, berkarya, dan menemukan jawaban.\n\nMenggabungkan kecanggihan Large Language Model dengan antarmuka yang ramah, Aksara AI hadir untuk meningkatkan produktivitas dan kreativitasmu sehari-hari.',
    
    // Features Description in About Page
    'feat_title_assist': 'Aksara Assistant',
    'feat_desc_assist': 'Chatbot cerdas yang siap menjawab pertanyaanmu, membantumu menulis, atau sekadar teman mengobrol.',
    'feat_title_face': 'Pengenalan Wajah',
    'feat_desc_face': 'Teknologi biometrik canggih untuk mengidentifikasi dan memverifikasi wajah secara real-time.',
    'feat_title_ocr': 'Pemindaian Teks (OCR)',
    'feat_desc_ocr': 'Ubah gambar dokumen fisik menjadi teks digital yang bisa diedit hanya dalam hitungan detik.',
    'feat_title_obj': 'Deteksi Objek',
    'feat_desc_obj': 'Arahkan kameramu ke benda di sekitarmu, dan AI akan memberitahumu benda apa itu.',
    'feat_title_music': 'Aksara Music',
    'feat_desc_music': 'Jelaskan musik yang ingin kamu dengar, dan AI akan membuatkannya untukmu.',

    // Developers Roles
    'role_ai': 'AI Engineer',
    'role_mobile': 'Mobile Developer',
    'role_ui': 'UI/UX Designer',

    // Privacy Policy Content
    'pp_last_updated': 'Terakhir diperbarui: 12 Desember 2025',
    'pp_1_title': '1. Pendahuluan',
    'pp_1_content': 'Kami di Aksara AI sangat menghargai privasi Anda. Kebijakan ini menjelaskan bagaimana kami mengumpulkan, menggunakan, dan melindungi data pribadi Anda saat menggunakan layanan kami.',
    'pp_2_title': '2. Data yang Kami Kumpulkan',
    'pp_2_content': 'Kami mengumpulkan informasi yang Anda berikan secara langsung, seperti data akun (Nama, Email), data biometrik wajah (jika fitur diaktifkan), dan riwayat percakapan dengan AI untuk meningkatkan kualitas respon.',
    'pp_3_title': '3. Penggunaan Informasi',
    'pp_3_content': 'Data Anda digunakan untuk:\n• Menyediakan dan memelihara layanan aplikasi.\n• Personalisasi pengalaman pengguna.\n• Meningkatkan keamanan dan deteksi penipuan.\n• Mengembangkan fitur AI baru.',
    'pp_4_title': '4. Keamanan Data',
    'pp_4_content': 'Kami menerapkan standar keamanan industri (enkripsi SSL/TLS) untuk melindungi data Anda. Data wajah disimpan dalam format terenkripsi dan tidak dibagikan ke pihak ketiga tanpa izin.',
    'pp_5_title': '5. Hak Pengguna',
    'pp_5_content': 'Anda berhak untuk mengakses, memperbaiki, atau menghapus data pribadi Anda kapan saja melalui menu Pengaturan di dalam aplikasi.',

    // Dashboard Cards (Short)
    'feat_face': 'Deteksi Wajah',
    'desc_face': 'Identifikasi wajah',
    'feat_ocr': 'Scan OCR',
    'desc_ocr': 'Ekstrak teks',
    'feat_music': 'Musik AI',
    'desc_music': 'Buat musik',
    'feat_obj': 'Deteksi Objek',
    'desc_obj': 'Kenali benda',
    'feat_qr': 'Scan QR',
    'desc_qr': 'Baca kode QR',

    // Assistant & Music
    'assist_title': 'Aksara Assistant',
    'assist_intro': 'Ada yang bisa saya bantu?',
    'assist_hint': 'Ketik pesan...',
    'music_player_title': 'Pemutar Musik',
    'unknown_song': 'Lagu Tidak Dikenal',
    'unknown_artist': 'Artis Tidak Dikenal',
    'now_playing': 'Sedang Diputar',
    
    // Settings
    'appearance': 'TAMPILAN',
    'dark_mode': 'Mode Gelap',
    'font_style': 'Gaya Huruf',
    'font_size': 'Ukuran Huruf',
    'system_data': 'SISTEM & DATA',
    'clear_cache': 'Bersihkan Cache',
    'cache_desc': 'Hapus data sementara',
    'cache_cleared': 'Cache dibersihkan!',
    'app_version': 'Versi Aplikasi',
    'select_language': 'Pilih Bahasa',
    'select_font': 'Pilih Jenis Huruf',

    // Profile
    'edit_name': 'Ubah Nama',
    'name_hint': 'Nama baru',
    'notif_name_desc': 'Nama berhasil diubah',
    'notif_photo_desc': 'Foto berhasil diubah',
    
    // Activity Logs
    'log_face_title': 'Deteksi Wajah',
    'log_face_desc': 'Mengakses fitur wajah',
    'log_ocr_title': 'OCR Scan',
    'log_ocr_desc': 'Melakukan scan teks',
    'log_music_title': 'Musik',
    'log_music_desc': 'Membuka musik',
    'log_obj_title': 'Deteksi Objek',
    'log_obj_desc': 'Deteksi benda',
    'log_qr_title': 'QR Scan',
    'log_qr_desc': 'Scan kode QR',
  },

  // ================= ENGLISH (EN) =================
  'en': {
    'app_name': 'Aksara AI',
    'hello': 'Hello,',
    'explore': 'Explore Features',
    'home': 'Home',
    'history': 'History',
    'profile': 'Profile',
    'settings': 'Settings',
    'about_app': 'About App',
    'privacy': 'Privacy Policy',
    'language': 'Language',
    'feedback': 'Feedback',
    'logout': 'Logout',
    'delete_account': 'Delete Account',
    'cancel': 'Cancel',
    'save': 'Save',
    'no_history': 'No activity history yet.',
    'no_notif': 'No new notifications.',

    'tab_bg': 'Background',
    'tab_feat': 'Main Features',
    'tab_dev': 'Developers',
    'about_bg_text': 'Aksara AI was born from a simple idea: what if everyone had a personal assistant ready to help anytime?\n\nIn the midst of information overload, we believe AI should simplify, not confuse. Aksara AI is built to be your smart companion in learning, creating, and finding answers.\n\nCombining LLM power with a friendly interface, Aksara AI is here to boost your daily productivity and creativity.',
    
    'feat_title_assist': 'Aksara Assistant',
    'feat_desc_assist': 'Smart chatbot ready to answer questions, help you write, or just chat.',
    'feat_title_face': 'Face Recognition',
    'feat_desc_face': 'Advanced biometric technology to identify and verify faces in real-time.',
    'feat_title_ocr': 'Text Scanning (OCR)',
    'feat_desc_ocr': 'Convert physical document images into editable digital text in seconds.',
    'feat_title_obj': 'Object Detection',
    'feat_desc_obj': 'Point your camera at objects around you, and AI will identify them.',
    'feat_title_music': 'Aksara Music',
    'feat_desc_music': 'Describe the music you want to hear, and AI will generate it for you.',

    'role_ai': 'AI Engineer',
    'role_mobile': 'Mobile Developer',
    'role_ui': 'UI/UX Designer',

    'pp_last_updated': 'Last updated: December 12, 2025',
    'pp_1_title': '1. Introduction',
    'pp_1_content': 'We at Aksara AI value your privacy. This policy explains how we collect, use, and protect your personal data when using our services.',
    'pp_2_title': '2. Data Collection',
    'pp_2_content': 'We collect information provided directly by you, such as account data (Name, Email), facial biometric data (if enabled), and AI conversation history.',
    'pp_3_title': '3. Information Usage',
    'pp_3_content': 'Your data is used to:\n• Provide and maintain services.\n• Personalize user experience.\n• Enhance security and fraud detection.\n• Develop new AI features.',
    'pp_4_title': '4. Data Security',
    'pp_4_content': 'We implement industry-standard security (SSL/TLS encryption) to protect your data. Facial data is stored encrypted and not shared with third parties.',
    'pp_5_title': '5. User Rights',
    'pp_5_content': 'You have the right to access, correct, or delete your personal data at any time via the Settings menu.',

    'feat_face': 'Face ID',
    'desc_face': 'Identify faces',
    'feat_ocr': 'OCR Scan',
    'desc_ocr': 'Extract text',
    'feat_music': 'AI Music',
    'desc_music': 'Create music',
    'feat_obj': 'Object ID',
    'desc_obj': 'Identify objects',
    'feat_qr': 'QR Scan',
    'desc_qr': 'Read QR codes',

    'assist_title': 'Aksara Assistant',
    'assist_intro': 'How can I help?',
    'assist_hint': 'Type a message...',
    'music_player_title': 'Music Player',
    'unknown_song': 'Unknown Song',
    'unknown_artist': 'Unknown Artist',
    'now_playing': 'Now Playing',

    'appearance': 'APPEARANCE',
    'dark_mode': 'Dark Mode',
    'font_style': 'Font Style',
    'font_size': 'Font Size',
    'system_data': 'SYSTEM & DATA',
    'clear_cache': 'Clear Cache',
    'cache_desc': 'Delete temp data',
    'cache_cleared': 'Cache cleared!',
    'app_version': 'App Version',
    'select_language': 'Select Language',
    'select_font': 'Select Font',

    'edit_name': 'Edit Name',
    'name_hint': 'New name',
    'notif_name_desc': 'Name updated',
    'notif_photo_desc': 'Photo updated',

    'log_face_title': 'Face Detection',
    'log_face_desc': 'Accessed face ID',
    'log_ocr_title': 'OCR Scan',
    'log_ocr_desc': 'Scanned text',
    'log_music_title': 'Music',
    'log_music_desc': 'Opened music',
    'log_obj_title': 'Object ID',
    'log_obj_desc': 'Object detected',
    'log_qr_title': 'QR Scan',
    'log_qr_desc': 'Scanned QR',
  },

  // ================= CHINESE (ZH) =================
  'zh': {
    'app_name': 'Aksara AI',
    'hello': '你好,',
    'explore': '探索功能',
    'home': '首页',
    'history': '历史',
    'profile': '我的',
    'settings': '设置',
    'about_app': '关于应用',
    'privacy': '隐私政策',
    'language': '语言',
    'feedback': '反馈',
    'logout': '登出',
    'delete_account': '删除账户',
    'cancel': '取消',
    'save': '保存',
    'no_history': '暂无历史记录',
    'no_notif': '暂无通知',

    'tab_bg': '背景',
    'tab_feat': '主要功能',
    'tab_dev': '开发者',
    'about_bg_text': 'Aksara AI 诞生于一个简单的想法：如果每个人都有一个随时准备提供帮助的私人助手会怎样？\n\n在信息过载的时代，我们相信人工智能应该简化生活，而不是令人困惑。Aksara AI 旨在成为您学习、创作和寻找答案的智能伙伴。',
    
    'feat_title_assist': 'Aksara 助手',
    'feat_desc_assist': '智能聊天机器人，随时准备回答您的问题。',
    'feat_title_face': '人脸识别',
    'feat_desc_face': '先进的生物识别技术，可实时识别和验证人脸。',
    'feat_title_ocr': '文本扫描 (OCR)',
    'feat_desc_ocr': '将物理文档图像转换为可编辑的数字文本。',
    'feat_title_obj': '物体检测',
    'feat_desc_obj': '识别周围的物体。',
    'feat_title_music': 'Aksara 音乐',
    'feat_desc_music': '为您生成想要的音乐。',

    'role_ai': 'AI 工程师',
    'role_mobile': '移动开发',
    'role_ui': 'UI/UX 设计师',

    'pp_last_updated': '最后更新：2025年12月12日',
    'pp_1_title': '1. 简介',
    'pp_1_content': 'Aksara AI 非常重视您的隐私。本政策说明我们如何收集、使用和保护您的个人数据。',
    'pp_2_title': '2. 数据收集',
    'pp_2_content': '我们收集您提供的账户数据（姓名、电子邮件）和生物识别数据。',
    'pp_3_title': '3. 信息使用',
    'pp_3_content': '数据用于提供服务、个性化体验和提高安全性。',
    'pp_4_title': '4. 数据安全',
    'pp_4_content': '我们使用 SSL/TLS 加密保护您的数据。',
    'pp_5_title': '5. 用户权利',
    'pp_5_content': '您有权访问、更正或删除您的数据。',

    'feat_face': '人脸识别',
    'desc_face': '识别身份',
    'feat_ocr': 'OCR 扫描',
    'desc_ocr': '提取文本',
    'feat_music': 'AI 音乐',
    'desc_music': '创作音乐',
    'feat_obj': '物体检测',
    'desc_obj': '识别物体',
    'feat_qr': 'QR 扫描',
    'desc_qr': '扫描二维码',

    'assist_title': 'Aksara 助手',
    'assist_intro': '有什么可以帮您？',
    'assist_hint': '输入消息...',
    'music_player_title': '音乐播放器',
    'unknown_song': '未知歌曲',
    'unknown_artist': '未知艺术家',
    'now_playing': '正在播放',

    'appearance': '外观',
    'dark_mode': '深色模式',
    'font_style': '字体样式',
    'font_size': '字体大小',
    'system_data': '系统数据',
    'clear_cache': '清除缓存',
    'cache_desc': '删除临时数据',
    'cache_cleared': '缓存已清除',
    'app_version': '版本',
    'select_language': '选择语言',
    'select_font': '选择字体',

    'edit_name': '修改名称',
    'name_hint': '新名称',
    'notif_name_desc': '名称已更新',
    'notif_photo_desc': '头像已更新',

    'log_face_title': '人脸检测',
    'log_face_desc': '使用人脸功能',
    'log_ocr_title': 'OCR 扫描',
    'log_ocr_desc': '扫描文本',
    'log_music_title': '音乐',
    'log_music_desc': '打开音乐',
    'log_obj_title': '物体检测',
    'log_obj_desc': '检测物体',
    'log_qr_title': 'QR 扫描',
    'log_qr_desc': '扫描二维码',
  },

  // ================= JAPANESE (JA) =================
  'ja': {
    'app_name': 'Aksara AI',
    'hello': 'こんにちは、',
    'explore': '機能',
    'home': 'ホーム',
    'history': '履歴',
    'profile': 'マイページ',
    'settings': '設定',
    'about_app': 'アプリについて',
    'privacy': 'プライバシー',
    'language': '言語',
    'feedback': 'フィードバック',
    'logout': 'ログアウト',
    'delete_account': 'アカウント削除',
    'cancel': 'キャンセル',
    'save': '保存',
    'no_history': '履歴なし',
    'no_notif': '通知なし',

    'tab_bg': '背景',
    'tab_feat': '主な機能',
    'tab_dev': '開発者',
    'about_bg_text': 'Aksara AIは、「誰もがいつでも助けてくれるパーソナルアシスタントを持っていたら？」というアイデアから生まれました。\n\n情報過多の時代、AIはシンプルであるべきです。Aksara AIは、学習や創作のスマートなパートナーです。',
    
    'feat_title_assist': 'Aksara アシスタント',
    'feat_desc_assist': '質問に答えたり、会話したりできるスマートチャットボット。',
    'feat_title_face': '顔認識',
    'feat_desc_face': 'リアルタイムで顔を識別する高度な生体認証技術。',
    'feat_title_ocr': 'テキストスキャン',
    'feat_desc_ocr': '画像の文字を編集可能なデジタルテキストに変換。',
    'feat_title_obj': '物体検出',
    'feat_desc_obj': 'カメラを向けるだけで物体を識別。',
    'feat_title_music': 'Aksara Music',
    'feat_desc_music': 'あなたのための音楽をAIが生成。',

    'role_ai': 'AIエンジニア',
    'role_mobile': 'モバイル開発',
    'role_ui': 'UI/UXデザイナー',

    'pp_last_updated': '更新日：2025年12月12日',
    'pp_1_title': '1. はじめに',
    'pp_1_content': 'Aksara AIはプライバシーを重視しています。本ポリシーはデータ収集と保護について説明します。',
    'pp_2_title': '2. データ収集',
    'pp_2_content': 'アカウント情報（名前、メール）および生体認証データを収集します。',
    'pp_3_title': '3. 利用目的',
    'pp_3_content': 'サービスの提供、パーソナライズ、セキュリティ向上に使用されます。',
    'pp_4_title': '4. セキュリティ',
    'pp_4_content': 'SSL/TLS暗号化でデータを保護します。',
    'pp_5_title': '5. ユーザーの権利',
    'pp_5_content': 'いつでもデータのアクセス、修正、削除が可能です。',

    'feat_face': '顔認識',
    'desc_face': '顔を識別',
    'feat_ocr': 'OCRスキャン',
    'desc_ocr': '文字抽出',
    'feat_music': 'AI音楽',
    'desc_music': '音楽生成',
    'feat_obj': '物体検出',
    'desc_obj': '物体識別',
    'feat_qr': 'QRスキャン',
    'desc_qr': 'コード読取',

    'assist_title': 'Aksara アシスタント',
    'assist_intro': 'お手伝いしますか？',
    'assist_hint': 'メッセージ...',
    'music_player_title': '音楽プレーヤー',
    'unknown_song': '不明な曲',
    'unknown_artist': '不明なアーティスト',
    'now_playing': '再生中',

    'appearance': '外観',
    'dark_mode': 'ダークモード',
    'font_style': 'フォント',
    'font_size': 'サイズ',
    'system_data': 'システム',
    'clear_cache': 'キャッシュ削除',
    'cache_desc': '一時データ削除',
    'cache_cleared': '完了しました',
    'app_version': 'バージョン',
    'select_language': '言語選択',
    'select_font': 'フォント選択',

    'edit_name': '名前変更',
    'name_hint': '新しい名前',
    'notif_name_desc': '名前更新完了',
    'notif_photo_desc': '写真更新完了',

    'log_face_title': '顔検出',
    'log_face_desc': '顔機能使用',
    'log_ocr_title': 'OCR',
    'log_ocr_desc': 'テキストスキャン',
    'log_music_title': '音楽',
    'log_music_desc': 'プレーヤー開く',
    'log_obj_title': '物体検出',
    'log_obj_desc': '物体検出使用',
    'log_qr_title': 'QR',
    'log_qr_desc': 'QRスキャン',
  },

  // ================= KOREAN (KO) =================
  'ko': {
    'app_name': 'Aksara AI',
    'hello': '안녕하세요,',
    'explore': '기능 탐색',
    'home': '홈',
    'history': '기록',
    'profile': '프로필',
    'settings': '설정',
    'about_app': '앱 정보',
    'privacy': '개인정보 정책',
    'language': '언어',
    'feedback': '피드백',
    'logout': '로그아웃',
    'delete_account': '계정 삭제',
    'cancel': '취소',
    'save': '저장',
    'no_history': '기록 없음',
    'no_notif': '알림 없음',

    'tab_bg': '배경',
    'tab_feat': '주요 기능',
    'tab_dev': '개발자',
    'about_bg_text': 'Aksara AI는 "모두가 언제든 도와줄 개인 비서가 있다면?"이라는 단순한 아이디어에서 시작되었습니다.\n\n정보 과부하 시대에 AI는 단순해야 합니다. Aksara AI는 학습과 창작의 스마트한 파트너입니다.',
    
    'feat_title_assist': 'Aksara 어시스턴트',
    'feat_desc_assist': '질문에 답하고 대화할 수 있는 스마트 챗봇.',
    'feat_title_face': '얼굴 인식',
    'feat_desc_face': '실시간으로 얼굴을 식별하는 고급 생체 인식 기술.',
    'feat_title_ocr': '텍스트 스캔 (OCR)',
    'feat_desc_ocr': '문서 이미지를 편집 가능한 텍스트로 변환.',
    'feat_title_obj': '객체 감지',
    'feat_desc_obj': '카메라로 주변 사물 식별.',
    'feat_title_music': 'Aksara 뮤직',
    'feat_desc_music': '원하는 음악을 AI가 생성.',

    'role_ai': 'AI 엔지니어',
    'role_mobile': '모바일 개발',
    'role_ui': 'UI/UX 디자이너',

    'pp_last_updated': '업데이트: 2025년 12월 12일',
    'pp_1_title': '1. 소개',
    'pp_1_content': 'Aksara AI는 귀하의 개인정보를 소중히 여깁니다. 본 정책은 데이터 수집 및 보호에 대해 설명합니다.',
    'pp_2_title': '2. 데이터 수집',
    'pp_2_content': '계정 정보(이름, 이메일) 및 생체 데이터를 수집합니다.',
    'pp_3_title': '3. 정보 사용',
    'pp_3_content': '서비스 제공, 개인화 및 보안 강화에 사용됩니다.',
    'pp_4_title': '4. 보안',
    'pp_4_content': 'SSL/TLS 암호화로 데이터를 보호합니다.',
    'pp_5_title': '5. 사용자 권리',
    'pp_5_content': '언제든지 데이터에 액세스하고 수정/삭제할 수 있습니다.',

    'feat_face': '얼굴 인식',
    'desc_face': '얼굴 식별',
    'feat_ocr': 'OCR 스캔',
    'desc_ocr': '텍스트 추출',
    'feat_music': 'AI 뮤직',
    'desc_music': '음악 생성',
    'feat_obj': '객체 감지',
    'desc_obj': '사물 식별',
    'feat_qr': 'QR 스캔',
    'desc_qr': 'QR 코드 스캔',

    'assist_title': 'Aksara 어시스턴트',
    'assist_intro': '무엇을 도와드릴까요?',
    'assist_hint': '메시지 입력...',
    'music_player_title': '뮤직 플레이어',
    'unknown_song': '알 수 없는 노래',
    'unknown_artist': '알 수 없는 아티스트',
    'now_playing': '재생 중',

    'appearance': '화면',
    'dark_mode': '다크 모드',
    'font_style': '글꼴',
    'font_size': '크기',
    'system_data': '시스템',
    'clear_cache': '캐시 삭제',
    'cache_desc': '임시 데이터 삭제',
    'cache_cleared': '완료됨',
    'app_version': '버전',
    'select_language': '언어 선택',
    'select_font': '글꼴 선택',

    'edit_name': '이름 변경',
    'name_hint': '새 이름',
    'notif_name_desc': '이름 업데이트됨',
    'notif_photo_desc': '사진 업데이트됨',

    'log_face_title': '얼굴 감지',
    'log_face_desc': '얼굴 기능 사용',
    'log_ocr_title': 'OCR',
    'log_ocr_desc': '텍스트 스캔',
    'log_music_title': '음악',
    'log_music_desc': '플레이어 열기',
    'log_obj_title': '객체 감지',
    'log_obj_desc': '사물 감지',
    'log_qr_title': 'QR',
    'log_qr_desc': 'QR 스캔',
  },
};